### ISSUE TITLE
机箱后面的USB3.0接口无法使用

### ISSUE THREAD

**Issue by cxp863** [i0Ek3/MSI-B460M-i5-10400-Hackintosh#1]
机箱后面的USB3.0接口无法正常使用，测试闪迪U盘以及SSD移动硬盘都不行

**Comment by i0Ek3** [comment]
抱歉一直没有看到你的 issue，机箱不同的话，USB 接口需要自己定制的，具体可以参考[这里](https://apple.sqlsec.com/6-实用姿势/6-1.html)。
