### ISSUE TITLE
老哥 这配置文件能上13正式版吗 

### ISSUE THREAD

**Issue by Elymac** [i0Ek3/MSI-B460M-i5-10400-Hackintosh#2]
感谢老哥分享 自己折腾了2 3天了
同板同U无独显 DP输出 上传的这个版本后面有啥驱动更新了吗

**Comment by i0Ek3** [comment]
抱歉这么久才回复，工作原因，这个黑苹果已经出了二手，不再维护了。如果需要更新驱动，可以跟我提供的链接下载更新，对比版本后再操作，记得提前备份数据。
